macro(ToRelativePath outFiles fromDirectory inFiles)
	unset(tmpFiles)
	foreach(inFile ${inFiles})
		file(RELATIVE_PATH outFile "${fromDirectory}" "${inFile}")
		list(APPEND tmpFiles "${outFile}")
	endforeach()

	set(${outFiles} ${tmpFiles})
endmacro()

macro(qt_use_modules _target _link_type)
	if(NOT TARGET ${_target})
		message(FATAL_ERROR "The first argument to qt_use_modules must be an existing target.")
	endif()
	if("${_link_type}" STREQUAL "LINK_PUBLIC" OR "${_link_type}" STREQUAL "LINK_PRIVATE" )
		set(_qt4_modules ${ARGN})
		set(_qt4_link_type ${_link_type})
	else()
		set(_qt4_modules ${_link_type} ${ARGN})
	endif()

	if("${_qt4_modules}" STREQUAL "")
		message(FATAL_ERROR "qt_use_modules requires at least one Qt module to use.")
	endif()

	foreach(_module5 ${_qt4_modules})
		string(TOUPPER ${_module5} _module)
		if(NOT QT_QT${_module}_FOUND)
			message(FATAL_ERROR "qt_use_modules(): QT_QT${_module} *not* FOUND.")
		endif()
		set(QT_USE_QT${_module} 1)
	endforeach()

	include(${QT_USE_FILE})
	target_link_libraries(${_target} ${_qt4_link_type} ${QT_LIBRARIES})
	set_property(TARGET ${_target} APPEND PROPERTY INCLUDE_DIRECTORIES ${QT_INCLUDE_DIRS})
	set_property(TARGET ${_target} APPEND PROPERTY COMPILE_DEFINITIONS ${QT_COMPILE_DEFINITIONS})
	set_property(TARGET ${_target} APPEND PROPERTY COMPILE_DEFINITIONS_RELEASE QT_NO_DEBUG)

	if(Qt_POSITION_INDEPENDENT_CODE)
		set_property(TARGET ${_target} PROPERTY POSITION_INDEPENDENT_CODE ${Qt_POSITION_INDEPENDENT_CODE})
	endif()
endmacro()